### ISSUE TITLE
Error with: name 'delids' is not defined 

### ISSUE THREAD

**Issue by ICLzhang** [milvus-io/milvus-tools#50]
- Encountered an issue when trying to migrate another dataset using DM tool 2.0 (New issues need to be resolved)
- 2022-09-20 05:23:11,401 ｜ ERROR ｜ milvus_to_milvus.py ｜ transform_milvus_data ｜ 47 ｜ Error with: name 'delids' is not defined

**Comment by yhmo** [comment]
This is a known issue, has been fixed by this commit: https://github.com/milvus-io/milvus-tools/commit/41143e5f4f5ef3693e4abd903e6b443b98804cb4

But this fix was not packed into the latest release 2.0rc, because 2.0rc was released on June 29, 2021, this commit was submitted on Aug 23, 2021.

Before we publish next release, you can manually fix it on your local:
1. find out the install path of pymilvusdm
2. find out the file pymilvusdm/core/read_milvus_data.py
3. change the "delids[2:]" to be "del_ids[2:]" at line no.51
